print("John Lennon's Imagine shortened\n")
print("Imagine there's no heaven")
print("It's easy if you try")
print("No hell below us")
print("Above us only sky")
print("Imagine all the people living for today\n")
print("Imagine there's no countries")
print("It isn't hard to do")
print("Nothing to kill or die for")
print("And no religion too")
print("Imagine all the people living life in peace\n")
print("You may say I'm a dreamer")
print("But I'm not the only one")
print("I hope some day you'll join us")
print("And the world will be as one")
